config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  namespace :admin do
    resources :products
    resources :shops
    resources :taxons

    root to: redirect('/admin/shops')
  end
  
  resources :shops, only: [:index, :show], param: :slug
  root to: 'shops#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :shop
  has_and_belongs_to_many :taxons
end

app/models/shop.rb
class Shop < ApplicationRecord
  has_many :products, dependent: :delete_all
  has_and_belongs_to_many :taxons

  scope :now_available, -> { where(["available_on <= ?", DateTime.now]) }
end

app/models/taxon.rb
class Taxon < ApplicationRecord
  has_and_belongs_to_many :shops
  has_and_belongs_to_many :products
end

app/controllers/admin/application_controller.rb
module Admin
  class ApplicationController < ActionController::Base
    layout 'admin'
  end
end

app/controllers/admin/products_controller.rb
module Admin
  class ProductsController < ApplicationController
    before_action :set_product, only: [:show, :edit, :update, :destroy]

    # GET /admin/products
    def index
      @products = Product.all
    end

    # GET /admin/products/1
    def show
    end

    # GET /admin/products/new
    def new
      @product = Product.new
    end

    # GET /admin/products/1/edit
    def edit
    end

    # POST /admin/products
    def create
      @product = Product.new(product_params)
      @product.taxon_ids = params[:product][:taxon_ids]

      if @product.save
        redirect_to [:admin, @product], notice: 'Product was successfully created.'
      else
        render :new
      end
    end

    # PATCH/PUT /admin/products/1
    def update
      if @product.update(product_params)
        @product.taxon_ids = params[:product][:taxon_ids]
        redirect_to [:admin, @product], notice: 'Product was successfully updated.'
      else
        render :edit
      end
    end

    # DELETE /admin/products/1
    def destroy
      @product.destroy

      redirect_to admin_products_url, notice: 'Product was successfully destroyed.'
    end

    private

    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def product_params
      params.require(:product).permit(:name, :description, :price, :shop_id)
    end
  end
end

app/controllers/admin/shops_controller.rb
module Admin
  class ShopsController < ApplicationController
    before_action :set_shop, only: [:show, :edit, :update, :destroy]

    # GET /admin/shops
    def index
      @shops = Shop.all
    end

    # GET /admin/shops/1
    def show
    end

    # GET /admin/shops/new
    def new
      @shop = Shop.new
    end

    # GET /admin/shops/1/edit
    def edit
    end

    # POST /admin/shops
    def create
      @shop = Shop.new(shop_params)
      @shop.taxon_ids = params[:shop][:taxon_ids]

      if @shop.save
        redirect_to [:admin, @shop], notice: 'Shop was successfully created.'
      else
        render :new
      end
    end

    # PATCH/PUT /admin/shops/1
    def update
      if @shop.update(shop_params)
        @shop.taxon_ids = params[:shop][:taxon_ids]
        redirect_to [:admin, @shop], notice: 'Shop was successfully updated.'
      else
        render :edit
      end
    end

    # DELETE /admin/shops/1
    def destroy
      @shop.destroy

      redirect_to admin_shops_url, notice: 'Shop was successfully destroyed.'
    end

    private

    # Use callbacks to share common setup or constraints between actions.
    def set_shop
      @shop = Shop.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def shop_params
      params.require(:shop).permit(:name, :slug, :available_on)
    end
  end
end

app/controllers/admin/taxons_controller.rb
module Admin
  class TaxonsController < ApplicationController
    before_action :set_taxon, only: [:show, :edit, :update, :destroy]

    # GET /admin/taxons
    def index
      @taxons = Taxon.all
    end

    # GET /admin/taxons/1
    def show
    end

    # GET /admin/taxons/new
    def new
      @taxon = Taxon.new
    end

    # GET /admin/taxons/1/edit
    def edit
    end

    # POST /admin/taxons
    def create
      @taxon = Taxon.new(taxon_params)

      if @taxon.save
        redirect_to [:admin, @taxon], notice: 'Taxon was successfully created.'
      else
        render :new
      end
    end

    # PATCH/PUT /admin/taxons/1
    def update
      if @taxon.update(taxon_params)
        redirect_to [:admin, @taxon], notice: 'Taxon was successfully updated.'
      else
        render :edit
      end
    end

    # DELETE /admin/taxons/1
    def destroy
      @taxon.destroy
      redirect_to admin_taxons_url, notice: 'Taxon was successfully destroyed.'
    end

    private

    # Use callbacks to share common setup or constraints between actions.
    def set_taxon
      @taxon = Taxon.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def taxon_params
      params.require(:taxon).permit(:name)
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/shops_controller.rb
class ShopsController < ApplicationController
  before_action :get_categories, only: [:index, :show]
  before_action :set_shop, only: [:show]

  def index
    if params[:category]
      @taxon = Taxon.find_by(name: params[:category])
      @shops = Shop.now_available.each_with_object([]) do |shop, arr|
        shop.taxons.each { |taxon| arr << shop if taxon == @taxon }
      end
    else
      @shops = Shop.now_available
    end
  end

  def show
    @products = @shop.products
  end

  private

  def set_shop
    @shop = Shop.find_by(slug: params[:slug])
  end

  def get_categories
    @categories = Taxon.all.each_with_object([]) do |taxon, arr|
      Shop.now_available.each { |shop| arr << taxon if (shop.taxons.include?(taxon)) }
    end
    @categories.uniq!
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/shops_helper.rb
module ShopsHelper
end

app/views/admin/products/_form.html.erb
<%= form_with(model: [:admin, product], local: true) do |form| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
        <% product.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.number_field :price %>
  </div>

  <div class="field">
    <%= form.label :shop %>
    <%= form.collection_select(:shop_id, Shop.all, :id, :name, prompt: true) %>
  </div>

  <div class="field">
    <%= form.label :taxons %>
    <%= form.collection_select(:taxon_ids, Taxon.all, :id, :name, {}, multiple: true) %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/admin/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', [:admin, @product] %> |
<%= link_to 'Back', admin_products_path %>

app/views/admin/products/index.html.erb
<h1>Products</h1>

<table>
  <thead>
    <tr>
      <th>Shop</th>
      <th>Name</th>
      <th>Price</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.shop.name %></td>
        <td><%= product.name %></td>
        <td><%= product.price %></td>
        <td><%= link_to 'Show', admin_product_path(product) %></td>
        <td><%= link_to 'Edit', edit_admin_product_path(product) %></td>
        <td><%= link_to 'Destroy', admin_product_path(product), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Product', new_admin_product_path %>

app/views/admin/products/new.html.erb
<h1>New Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', admin_products_path %>

app/views/admin/products/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @product.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @product.description %>
</p>

<p>
  <strong>Price:</strong>
  <%= @product.price %>
</p>

<p>
  <strong>Shop:</strong>
  <%= @product.shop.name %>
</p>

<p>
  <strong>Taxons:</strong>
  <ul>
    <% @product.taxons.each do |taxon| -%>
      <%= tag.li taxon.name %>
    <% end %>
  </ul>
</p>

<%= link_to 'Edit', edit_admin_product_path(@product) %> |
<%= link_to 'Back', admin_products_path %>

app/views/admin/shops/_form.html.erb
<%= form_with(model: [:admin, shop], local: true) do |form| %>
  <% if shop.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(shop.errors.count, "error") %> prohibited this shop from being saved:</h2>

      <ul>
        <% shop.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :slug %>
    <%= form.text_field :slug %>
  </div>

  <div class="field">
    <%= form.label :available_on %>
    <%= form.datetime_select :available_on %>
  </div>

  <div class="field">
    <%= form.label :taxons %>
    <%= form.select :taxon_ids, options_from_collection_for_select(Taxon.all, :id, :name), {}, multiple: true %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/admin/shops/edit.html.erb
<h1>Editing Shop</h1>

<%= render 'form', shop: @shop %>

<%= link_to 'Show', [:admin, @shop] %> |
<%= link_to 'Back', admin_shops_path %>

app/views/admin/shops/index.html.erb
<h1>Shops</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Slug</th>
      <th>Available to users</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @shops.each do |shop| %>
      <tr>
        <td><%= shop.name %></td>
        <td><%= shop.slug %></td>
        <td class="center">
          <% if shop.available_on && shop.available_on < Time.zone.now -%>
            ✅
          <% else -%>
            ❌
          <% end -%>
        </td>
        <td><%= link_to 'Show', [:admin, shop] %></td>
        <td><%= link_to 'Edit', edit_admin_shop_path(shop) %></td>
        <td><%= link_to 'Destroy', [:admin, shop], method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Shop', new_admin_shop_path %>

app/views/admin/shops/new.html.erb
<h1>New Shop</h1>

<%= render 'form', shop: @shop %>

<%= link_to 'Back', admin_shops_path %>

app/views/admin/shops/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @shop.name %>
</p>

<p>
  <strong>Available on:</strong>
  <%= @shop.available_on %>
</p>

<p>
  <strong>Taxons:</strong>
  <ul>
    <% @shop.taxons.each do |taxon| -%>
      <%= tag.li taxon.name %>
    <% end -%>
  </ul>
</p>

<%= link_to 'Edit', edit_admin_shop_path(@shop) %> |
<%= link_to 'Back', admin_shops_path %>

app/views/admin/taxons/_form.html.erb
<%= form_with(model: [:admin, taxon], local: true) do |form| %>
  <% if taxon.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(taxon.errors.count, "error") %> prohibited this taxon from being saved:</h2>

      <ul>
        <% taxon.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/admin/taxons/edit.html.erb
<h1>Editing Taxon</h1>

<%= render 'form', taxon: @taxon %>

<%= link_to 'Show', [:admin, @taxon] %> |
<%= link_to 'Back', admin_taxons_path %>

app/views/admin/taxons/index.html.erb
<h1>Taxons</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @taxons.each do |taxon| %>
      <tr>
        <td><%= taxon.name %></td>
        <td><%= link_to 'Show', [:admin, taxon] %></td>
        <td><%= link_to 'Edit', edit_admin_taxon_path(taxon) %></td>
        <td><%= link_to 'Destroy', [:admin, taxon], method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Taxon', new_admin_taxon_path %>

app/views/admin/taxons/new.html.erb
<h1>New Taxon</h1>

<%= render 'form', taxon: @taxon %>

<%= link_to 'Back', admin_taxons_path %>

app/views/admin/taxons/show.html.erb
<h1><%= @taxon.name %></h1>

<h3>Shops</h3>
<ul>
  <% @taxon.shops.each do |shop| -%>
    <%= tag.li link_to(shop.name, [:admin, shop]) %>
  <% end -%>
</ul>


<h3>Products</h3>
<ul>
  <% @taxon.products.each do |product| -%>
    <%= tag.li link_to(product.name, [:admin, product]) %>
  <% end -%>
</ul>

<%= link_to 'Edit', edit_admin_taxon_path(@taxon) %> |
<%= link_to 'Back', admin_taxons_path %>

app/views/layouts/_nav.html.erb
<header>
  <%= link_to "All shops", shops_path, class: 'all' %>
  <ul class='list' >
    <% @categories.each do |categorie| %>
      <li><%= link_to categorie.name, shops_path(category: categorie.name) %></li>
    <% end %>
  </ul>
</header>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TestTechnique - Back Office</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'admin', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'admin', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav id="menu">
      <ul>
        <li><%= link_to 'Shops',    admin_shops_path %></li>
        <li><%= link_to 'Products', admin_products_path %></li>
        <li><%= link_to 'Taxons',   admin_taxons_path %></li>
      </ul>
    </nav>
    <div id="content">
      <p id="notice"><%= notice %></p>

      <%= yield %>
    </div>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TestTechnique</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "layouts/nav"  %>
    <%= yield %>
  </body>
</html>

app/views/shops/_product_card.html.erb
<div class="products-item-details">
  <img src="https://source.unsplash.com/featured/?<%= taxon.name %>" />
  <div class="products-item-infos">
    <h2><%= product.name %></h2>
    <p><%= product.description %></p>
    <p><%= product.price %> €</p>
  </div>
</div>

app/views/shops/_shop.html.erb
<div class="card">
  <img src="https://source.unsplash.com/featured/?<%= shop.taxons.first ? shop.taxons.first.name : "vegetable" %>" />
  <div class="card-infos">
    <div>
      <h2><%= shop.name %></h2>
      <p class="taxons">
        <% shop.taxons.each do |taxon| %>
          <span><%= taxon.name %></span>
        <% end %>
      </p>
    </div>
  </div>
</div>

app/views/shops/index.html.erb
<div class="cards">
  <% @shops.each do |shop| %>
    <%= link_to shop_path(shop.slug) do %>
      <%= render shop %>
    <% end %>
  <% end %>
</div>

app/views/shops/show.html.erb
<div class="card-shop" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://source.unsplash.com/featured/?<%= @shop.taxons.first ? @shop.taxons.first.name : "vegetable" %>)">
  <%= @shop.name %>
</div>

<% if @products.any? %>
  <div class="wrapper">
    <!-- we display a list of the available categories -->
    <div class="categories">
      <% @shop.taxons.each do |taxon| %>
        <!-- we display only the ones which aren't empty -->
        <% if taxon.products.where(shop: @shop).any? %>
          <div class="categories-item">
            <%= taxon.name %>
          </div>
        <% end %>
      <% end %>
    </div>

    <div class="products">
      <% @shop.taxons.each do |taxon| %>
        <!-- we check if the shops' categories have a product as above -->
        <% if taxon.products.where(shop: @shop).any? %>
          <h2><%= taxon.name %></h2>
          <!-- if yes, we display a card of the product -->
          <div class="products-item">
            <% @products.each do |product| %>
              <!-- with only the right product for the right taxon -->
              <% if product.taxons.include?(taxon) %>
                <%= render partial: "shops/product_card", locals: { product: product, taxon: taxon } %>
              <% end %>
            <% end %>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>

<% else %>
  <h1 style="text-align: center; margin-top: 50px;">Sorry this shop doesn't have any products yet.</h1>
<% end %>